### ISSUE TITLE
sentry-cli command not found

### ISSUE THREAD

**Issue by ChristianVermeulen** [mathieu-bour/setup-sentry-cli#4]
For some reason, my runner still can not find my sentry cli command...

My github action config:
```
	- name: Setup Sentry CLI
        uses: mathrix-education/setup-sentry-cli@0.1.0
        with:
          version: latest # optional if 'latest'
          url: https://sentry.io
          token: ${{ secrets.SENTRY_AUTH_TOKEN }} # from GitHub secrets
          organization: itexperts
          project: webreporttool
```

The result in the action runner (which looks good to me):
![Screenshot 2020-09-30 at 10 45 41](https://user-images.githubusercontent.com/1062751/94663816-6987dd00-030a-11eb-8ebb-ad7b59d89626.png)

When actually calling the `sentry-cli` command:
![Screenshot 2020-09-30 at 10 46 01](https://user-images.githubusercontent.com/1062751/94663875-7a385300-030a-11eb-8272-a2c919a76b35.png)

Am I missing something here?
